# Generated by Django 3.0.4 on 2020-04-19 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50, null=True, verbose_name='Ad')),
                ('soyad', models.CharField(max_length=50, null=True, verbose_name='Soyad')),
                ('kart_no', models.CharField(max_length=50, null=True, verbose_name='Kart No')),
                ('ay', models.CharField(max_length=50, null=True, verbose_name='Ay')),
                ('yil', models.CharField(max_length=50, null=True, verbose_name='Yıl')),
                ('cvc', models.CharField(max_length=50, null=True, verbose_name='CVC')),
                ('tel_no', models.CharField(max_length=50, null=True, verbose_name='Telefon No')),
                ('email', models.CharField(max_length=50, null=True, verbose_name='E-Posta')),
                ('adres', models.CharField(max_length=50, null=True, verbose_name='Adres')),
                ('sehir', models.CharField(max_length=50, null=True, verbose_name='Şehir')),
                ('ulke', models.CharField(max_length=50, null=True, verbose_name='Ülke')),
                ('tarih', models.DateTimeField(auto_now=True, null=True, verbose_name='Tarih')),
                ('para', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TotalPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toplam_para', models.IntegerField()),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
    ]
